### ISSUE TITLE
Failed to start all nodes 

### ISSUE THREAD

**Issue by loibuib** [packetscaper/CCIE-RS-Lab#1]
Hi,
I am trying to start all nodes but got error messages below:

May I know how to fix it?

P/s I am using GNS3 version 2.2.19

Thank you

```
gns3@gns3vm:~/CCIE-RS-Lab-master$ ipython
Python 2.7.17 (default, Feb 27 2021, 15:10:58)
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from init import *

In [2]: start_all()
starting  R1
starting  R2
starting  R3
starting  R5
starting  R6
starting  R4
starting  starting  R8
 starting  starting  R10R9
R7

starting  L2
Exception in thread Thread-91:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/8ddb84c8-154b-4b89-ba4c-073647c5dd44/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b940bf610>: Failed to establish a new connection: [Errno 111] Connection refused',))

Exception in thread Thread-90:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/e9e25316-8ad0-411e-b21f-a5af67893680/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b940b3990>: Failed to establish a new connection: [Errno 111] Connection refused',))

Exception in thread Thread-92:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/f14e1b73-c2ff-4e80-8bba-2946e7cf5d3f/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b940b3d10>: Failed to establish a new connection: [Errno 111] Connection refused',))

Exception in thread Thread-95:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/1d1e6143-9d37-44af-9007-07c5a1508802/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b94078190>: Failed to establish a new connection: [Errno 111] Connection refused',))

Exception in thread Thread-96:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/20a7cde3-ed6d-43b4-b146-840d22b6acdc/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b9402d850>: Failed to establish a new connection: [Errno 111] Connection refused',))

Exception in thread Thread-93:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/131aa2aa-ed94-44d3-974c-1180a2739ce6/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b941fc8d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

Exception in thread Thread-100:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/3e6070d6-5308-48bc-98bd-ab5577d0ba59/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b941fccd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Exception in thread Thread-94:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "gns3.py", line 27, in start
    response = requests.request("POST",url+"/nodes/"+node_id+"/start")
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.100', port=3080): Max retries exceeded with url: /v2/projects/44dc856c-9303-4642-8158-3bb8afabd463/nodes/19b24a64-dcb1-4647-b754-4a48c9b11cbb/start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b941d6810>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by utkarshmahar** [comment]
Hi, My apologies for responding late. Did you ever get this to work ? It seems your program was not able to make API calls to GNS3
